packages:
  - playground/**
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
catalog:
  tsdown: ^0.18.3
  unbuild: ^3.6.1
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@typescript/native-preview'
  - oxfmt
  - oxlint
